"""统一错误码定义 — 对应 SPEC 9.3。"""

from enum import StrEnum


class ErrorCode(StrEnum):
    """系统统一错误码。"""

    # Skill
    SKILL_NOT_FOUND = "SKILL_NOT_FOUND"
    SKILL_DISABLED = "SKILL_DISABLED"

    # Schema
    SCHEMA_VALIDATION_FAILED = "SCHEMA_VALIDATION_FAILED"

    # Sub-Agent
    SUBAGENT_TIMEOUT = "SUBAGENT_TIMEOUT"

    # Tool
    TOOL_EXECUTION_FAILED = "TOOL_EXECUTION_FAILED"
    TOOL_NOT_ALLOWED = "TOOL_NOT_ALLOWED"
    TOOL_APPROVAL_PENDING = "TOOL_APPROVAL_PENDING"

    # Model
    UPSTREAM_MODEL_ERROR = "UPSTREAM_MODEL_ERROR"
    MODEL_FALLBACK = "MODEL_FALLBACK"

    # Context
    CONTEXT_OVERFLOW = "CONTEXT_OVERFLOW"

    # Agent
    MAX_STEPS_EXCEEDED = "MAX_STEPS_EXCEEDED"

    # Session
    SESSION_EXPIRED = "SESSION_EXPIRED"

    # Rate
    RATE_LIMITED = "RATE_LIMITED"

    # Vector
    VECTOR_WRITE_FAILED = "VECTOR_WRITE_FAILED"
    EMBEDDING_FAILED = "EMBEDDING_FAILED"

    # Channel
    CHANNEL_NOT_CONFIGURED = "CHANNEL_NOT_CONFIGURED"
    CHANNEL_SEND_FAILED = "CHANNEL_SEND_FAILED"
